# Generated by Django 4.1.7 on 2023-03-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_logs", "0002_entry"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entry",
            old_name="date_add",
            new_name="date_added",
        ),
        migrations.AddField(
            model_name="entry",
            name="text",
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
